import { Grid } from '@material-ui/core'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Navbar from './navbar'
import SideBar from './sidebar';
import SkillTest from './skilltest';

export default function Home() {

return (
<div className='main-content'>
	<Head>
	<title>Cuvette | DashBoard</title>
	<meta name="description" content="Generated by create next app" />
	<link rel="icon" href="/favicon.ico" />
	</Head>
	<Navbar />
	<div className='main'>
	<Grid container>
		<Grid  item xs={2}>
			<SideBar />
		</Grid>
		<Grid  item xs={10}>
			<SkillTest />
		</Grid>
	</Grid>
	
	</div>
</div>
)
}
